/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialtiesRouteImport } from './routes/specialties'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LongevityRouteImport } from './routes/longevity'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialtiesIndexRouteImport } from './routes/specialties.index'
import { Route as SpecialtiesSleepMedicineRouteImport } from './routes/specialties.sleep-medicine'
import { Route as SpecialtiesPrimaryCareRouteImport } from './routes/specialties.primary-care'
import { Route as SpecialtiesPainManagementRouteImport } from './routes/specialties.pain-management'
import { Route as SpecialtiesNeurologyRouteImport } from './routes/specialties.neurology'
import { Route as SpecialtiesCardiologyVascularRouteImport } from './routes/specialties.cardiology-vascular'

const SpecialtiesRoute = SpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LongevityRoute = LongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesIndexRoute = SpecialtiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecialtiesRoute,
} as any)
const SpecialtiesSleepMedicineRoute =
  SpecialtiesSleepMedicineRouteImport.update({
    id: '/sleep-medicine',
    path: '/sleep-medicine',
    getParentRoute: () => SpecialtiesRoute,
  } as any)
const SpecialtiesPrimaryCareRoute = SpecialtiesPrimaryCareRouteImport.update({
  id: '/primary-care',
  path: '/primary-care',
  getParentRoute: () => SpecialtiesRoute,
} as any)
const SpecialtiesPainManagementRoute =
  SpecialtiesPainManagementRouteImport.update({
    id: '/pain-management',
    path: '/pain-management',
    getParentRoute: () => SpecialtiesRoute,
  } as any)
const SpecialtiesNeurologyRoute = SpecialtiesNeurologyRouteImport.update({
  id: '/neurology',
  path: '/neurology',
  getParentRoute: () => SpecialtiesRoute,
} as any)
const SpecialtiesCardiologyVascularRoute =
  SpecialtiesCardiologyVascularRouteImport.update({
    id: '/cardiology-vascular',
    path: '/cardiology-vascular',
    getParentRoute: () => SpecialtiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/locations': typeof LocationsRoute
  '/longevity': typeof LongevityRoute
  '/resources': typeof ResourcesRoute
  '/specialties': typeof SpecialtiesRouteWithChildren
  '/specialties/cardiology-vascular': typeof SpecialtiesCardiologyVascularRoute
  '/specialties/neurology': typeof SpecialtiesNeurologyRoute
  '/specialties/pain-management': typeof SpecialtiesPainManagementRoute
  '/specialties/primary-care': typeof SpecialtiesPrimaryCareRoute
  '/specialties/sleep-medicine': typeof SpecialtiesSleepMedicineRoute
  '/specialties/': typeof SpecialtiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/locations': typeof LocationsRoute
  '/longevity': typeof LongevityRoute
  '/resources': typeof ResourcesRoute
  '/specialties/cardiology-vascular': typeof SpecialtiesCardiologyVascularRoute
  '/specialties/neurology': typeof SpecialtiesNeurologyRoute
  '/specialties/pain-management': typeof SpecialtiesPainManagementRoute
  '/specialties/primary-care': typeof SpecialtiesPrimaryCareRoute
  '/specialties/sleep-medicine': typeof SpecialtiesSleepMedicineRoute
  '/specialties': typeof SpecialtiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/locations': typeof LocationsRoute
  '/longevity': typeof LongevityRoute
  '/resources': typeof ResourcesRoute
  '/specialties': typeof SpecialtiesRouteWithChildren
  '/specialties/cardiology-vascular': typeof SpecialtiesCardiologyVascularRoute
  '/specialties/neurology': typeof SpecialtiesNeurologyRoute
  '/specialties/pain-management': typeof SpecialtiesPainManagementRoute
  '/specialties/primary-care': typeof SpecialtiesPrimaryCareRoute
  '/specialties/sleep-medicine': typeof SpecialtiesSleepMedicineRoute
  '/specialties/': typeof SpecialtiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/locations'
    | '/longevity'
    | '/resources'
    | '/specialties'
    | '/specialties/cardiology-vascular'
    | '/specialties/neurology'
    | '/specialties/pain-management'
    | '/specialties/primary-care'
    | '/specialties/sleep-medicine'
    | '/specialties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/locations'
    | '/longevity'
    | '/resources'
    | '/specialties/cardiology-vascular'
    | '/specialties/neurology'
    | '/specialties/pain-management'
    | '/specialties/primary-care'
    | '/specialties/sleep-medicine'
    | '/specialties'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/locations'
    | '/longevity'
    | '/resources'
    | '/specialties'
    | '/specialties/cardiology-vascular'
    | '/specialties/neurology'
    | '/specialties/pain-management'
    | '/specialties/primary-care'
    | '/specialties/sleep-medicine'
    | '/specialties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LocationsRoute: typeof LocationsRoute
  LongevityRoute: typeof LongevityRoute
  ResourcesRoute: typeof ResourcesRoute
  SpecialtiesRoute: typeof SpecialtiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialties': {
      id: '/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof SpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longevity': {
      id: '/longevity'
      path: '/longevity'
      fullPath: '/longevity'
      preLoaderRoute: typeof LongevityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/': {
      id: '/specialties/'
      path: '/'
      fullPath: '/specialties/'
      preLoaderRoute: typeof SpecialtiesIndexRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/sleep-medicine': {
      id: '/specialties/sleep-medicine'
      path: '/sleep-medicine'
      fullPath: '/specialties/sleep-medicine'
      preLoaderRoute: typeof SpecialtiesSleepMedicineRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/primary-care': {
      id: '/specialties/primary-care'
      path: '/primary-care'
      fullPath: '/specialties/primary-care'
      preLoaderRoute: typeof SpecialtiesPrimaryCareRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/pain-management': {
      id: '/specialties/pain-management'
      path: '/pain-management'
      fullPath: '/specialties/pain-management'
      preLoaderRoute: typeof SpecialtiesPainManagementRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/neurology': {
      id: '/specialties/neurology'
      path: '/neurology'
      fullPath: '/specialties/neurology'
      preLoaderRoute: typeof SpecialtiesNeurologyRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/cardiology-vascular': {
      id: '/specialties/cardiology-vascular'
      path: '/cardiology-vascular'
      fullPath: '/specialties/cardiology-vascular'
      preLoaderRoute: typeof SpecialtiesCardiologyVascularRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
  }
}

interface SpecialtiesRouteChildren {
  SpecialtiesCardiologyVascularRoute: typeof SpecialtiesCardiologyVascularRoute
  SpecialtiesNeurologyRoute: typeof SpecialtiesNeurologyRoute
  SpecialtiesPainManagementRoute: typeof SpecialtiesPainManagementRoute
  SpecialtiesPrimaryCareRoute: typeof SpecialtiesPrimaryCareRoute
  SpecialtiesSleepMedicineRoute: typeof SpecialtiesSleepMedicineRoute
  SpecialtiesIndexRoute: typeof SpecialtiesIndexRoute
}

const SpecialtiesRouteChildren: SpecialtiesRouteChildren = {
  SpecialtiesCardiologyVascularRoute: SpecialtiesCardiologyVascularRoute,
  SpecialtiesNeurologyRoute: SpecialtiesNeurologyRoute,
  SpecialtiesPainManagementRoute: SpecialtiesPainManagementRoute,
  SpecialtiesPrimaryCareRoute: SpecialtiesPrimaryCareRoute,
  SpecialtiesSleepMedicineRoute: SpecialtiesSleepMedicineRoute,
  SpecialtiesIndexRoute: SpecialtiesIndexRoute,
}

const SpecialtiesRouteWithChildren = SpecialtiesRoute._addFileChildren(
  SpecialtiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LocationsRoute: LocationsRoute,
  LongevityRoute: LongevityRoute,
  ResourcesRoute: ResourcesRoute,
  SpecialtiesRoute: SpecialtiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
