/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialtiesRouteImport } from './routes/specialties'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LongevityRouteImport } from './routes/longevity'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpecialtiesIndexRouteImport } from './routes/specialties.index'
import { Route as DiagnosticsIndexRouteImport } from './routes/diagnostics.index'
import { Route as SpecialtiesSleepMedicineRouteImport } from './routes/specialties.sleep-medicine'
import { Route as SpecialtiesPrimaryCareRouteImport } from './routes/specialties.primary-care'
import { Route as SpecialtiesPainManagementRouteImport } from './routes/specialties.pain-management'
import { Route as SpecialtiesNeurologyRouteImport } from './routes/specialties.neurology'
import { Route as SpecialtiesCardiologyVascularRouteImport } from './routes/specialties.cardiology-vascular'
import { Route as DiagnosticsSleepPulmonaryRouteImport } from './routes/diagnostics.sleep-pulmonary'
import { Route as DiagnosticsSampleReportRouteImport } from './routes/diagnostics.sample-report'
import { Route as DiagnosticsImagingCardiacRouteImport } from './routes/diagnostics.imaging-cardiac'
import { Route as DiagnosticsCancerScreeningRouteImport } from './routes/diagnostics.cancer-screening'
import { Route as DiagnosticsBiomarkersRouteImport } from './routes/diagnostics.biomarkers'
import { Route as DiagnosticsAutonomicTestingRouteImport } from './routes/diagnostics.autonomic-testing'
import { Route as DiagnosticsAllergyTestingRouteImport } from './routes/diagnostics.allergy-testing'

const SpecialtiesRoute = SpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LongevityRoute = LongevityRouteImport.update({
  id: '/longevity',
  path: '/longevity',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialtiesIndexRoute = SpecialtiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecialtiesRoute,
} as any)
const DiagnosticsIndexRoute = DiagnosticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnosticsRoute,
} as any)
const SpecialtiesSleepMedicineRoute =
  SpecialtiesSleepMedicineRouteImport.update({
    id: '/sleep-medicine',
    path: '/sleep-medicine',
    getParentRoute: () => SpecialtiesRoute,
  } as any)
const SpecialtiesPrimaryCareRoute = SpecialtiesPrimaryCareRouteImport.update({
  id: '/primary-care',
  path: '/primary-care',
  getParentRoute: () => SpecialtiesRoute,
} as any)
const SpecialtiesPainManagementRoute =
  SpecialtiesPainManagementRouteImport.update({
    id: '/pain-management',
    path: '/pain-management',
    getParentRoute: () => SpecialtiesRoute,
  } as any)
const SpecialtiesNeurologyRoute = SpecialtiesNeurologyRouteImport.update({
  id: '/neurology',
  path: '/neurology',
  getParentRoute: () => SpecialtiesRoute,
} as any)
const SpecialtiesCardiologyVascularRoute =
  SpecialtiesCardiologyVascularRouteImport.update({
    id: '/cardiology-vascular',
    path: '/cardiology-vascular',
    getParentRoute: () => SpecialtiesRoute,
  } as any)
const DiagnosticsSleepPulmonaryRoute =
  DiagnosticsSleepPulmonaryRouteImport.update({
    id: '/sleep-pulmonary',
    path: '/sleep-pulmonary',
    getParentRoute: () => DiagnosticsRoute,
  } as any)
const DiagnosticsSampleReportRoute = DiagnosticsSampleReportRouteImport.update({
  id: '/sample-report',
  path: '/sample-report',
  getParentRoute: () => DiagnosticsRoute,
} as any)
const DiagnosticsImagingCardiacRoute =
  DiagnosticsImagingCardiacRouteImport.update({
    id: '/imaging-cardiac',
    path: '/imaging-cardiac',
    getParentRoute: () => DiagnosticsRoute,
  } as any)
const DiagnosticsCancerScreeningRoute =
  DiagnosticsCancerScreeningRouteImport.update({
    id: '/cancer-screening',
    path: '/cancer-screening',
    getParentRoute: () => DiagnosticsRoute,
  } as any)
const DiagnosticsBiomarkersRoute = DiagnosticsBiomarkersRouteImport.update({
  id: '/biomarkers',
  path: '/biomarkers',
  getParentRoute: () => DiagnosticsRoute,
} as any)
const DiagnosticsAutonomicTestingRoute =
  DiagnosticsAutonomicTestingRouteImport.update({
    id: '/autonomic-testing',
    path: '/autonomic-testing',
    getParentRoute: () => DiagnosticsRoute,
  } as any)
const DiagnosticsAllergyTestingRoute =
  DiagnosticsAllergyTestingRouteImport.update({
    id: '/allergy-testing',
    path: '/allergy-testing',
    getParentRoute: () => DiagnosticsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/locations': typeof LocationsRoute
  '/longevity': typeof LongevityRoute
  '/resources': typeof ResourcesRoute
  '/specialties': typeof SpecialtiesRouteWithChildren
  '/diagnostics/allergy-testing': typeof DiagnosticsAllergyTestingRoute
  '/diagnostics/autonomic-testing': typeof DiagnosticsAutonomicTestingRoute
  '/diagnostics/biomarkers': typeof DiagnosticsBiomarkersRoute
  '/diagnostics/cancer-screening': typeof DiagnosticsCancerScreeningRoute
  '/diagnostics/imaging-cardiac': typeof DiagnosticsImagingCardiacRoute
  '/diagnostics/sample-report': typeof DiagnosticsSampleReportRoute
  '/diagnostics/sleep-pulmonary': typeof DiagnosticsSleepPulmonaryRoute
  '/specialties/cardiology-vascular': typeof SpecialtiesCardiologyVascularRoute
  '/specialties/neurology': typeof SpecialtiesNeurologyRoute
  '/specialties/pain-management': typeof SpecialtiesPainManagementRoute
  '/specialties/primary-care': typeof SpecialtiesPrimaryCareRoute
  '/specialties/sleep-medicine': typeof SpecialtiesSleepMedicineRoute
  '/diagnostics/': typeof DiagnosticsIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locations': typeof LocationsRoute
  '/longevity': typeof LongevityRoute
  '/resources': typeof ResourcesRoute
  '/diagnostics/allergy-testing': typeof DiagnosticsAllergyTestingRoute
  '/diagnostics/autonomic-testing': typeof DiagnosticsAutonomicTestingRoute
  '/diagnostics/biomarkers': typeof DiagnosticsBiomarkersRoute
  '/diagnostics/cancer-screening': typeof DiagnosticsCancerScreeningRoute
  '/diagnostics/imaging-cardiac': typeof DiagnosticsImagingCardiacRoute
  '/diagnostics/sample-report': typeof DiagnosticsSampleReportRoute
  '/diagnostics/sleep-pulmonary': typeof DiagnosticsSleepPulmonaryRoute
  '/specialties/cardiology-vascular': typeof SpecialtiesCardiologyVascularRoute
  '/specialties/neurology': typeof SpecialtiesNeurologyRoute
  '/specialties/pain-management': typeof SpecialtiesPainManagementRoute
  '/specialties/primary-care': typeof SpecialtiesPrimaryCareRoute
  '/specialties/sleep-medicine': typeof SpecialtiesSleepMedicineRoute
  '/diagnostics': typeof DiagnosticsIndexRoute
  '/specialties': typeof SpecialtiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/locations': typeof LocationsRoute
  '/longevity': typeof LongevityRoute
  '/resources': typeof ResourcesRoute
  '/specialties': typeof SpecialtiesRouteWithChildren
  '/diagnostics/allergy-testing': typeof DiagnosticsAllergyTestingRoute
  '/diagnostics/autonomic-testing': typeof DiagnosticsAutonomicTestingRoute
  '/diagnostics/biomarkers': typeof DiagnosticsBiomarkersRoute
  '/diagnostics/cancer-screening': typeof DiagnosticsCancerScreeningRoute
  '/diagnostics/imaging-cardiac': typeof DiagnosticsImagingCardiacRoute
  '/diagnostics/sample-report': typeof DiagnosticsSampleReportRoute
  '/diagnostics/sleep-pulmonary': typeof DiagnosticsSleepPulmonaryRoute
  '/specialties/cardiology-vascular': typeof SpecialtiesCardiologyVascularRoute
  '/specialties/neurology': typeof SpecialtiesNeurologyRoute
  '/specialties/pain-management': typeof SpecialtiesPainManagementRoute
  '/specialties/primary-care': typeof SpecialtiesPrimaryCareRoute
  '/specialties/sleep-medicine': typeof SpecialtiesSleepMedicineRoute
  '/diagnostics/': typeof DiagnosticsIndexRoute
  '/specialties/': typeof SpecialtiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/locations'
    | '/longevity'
    | '/resources'
    | '/specialties'
    | '/diagnostics/allergy-testing'
    | '/diagnostics/autonomic-testing'
    | '/diagnostics/biomarkers'
    | '/diagnostics/cancer-screening'
    | '/diagnostics/imaging-cardiac'
    | '/diagnostics/sample-report'
    | '/diagnostics/sleep-pulmonary'
    | '/specialties/cardiology-vascular'
    | '/specialties/neurology'
    | '/specialties/pain-management'
    | '/specialties/primary-care'
    | '/specialties/sleep-medicine'
    | '/diagnostics/'
    | '/specialties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/locations'
    | '/longevity'
    | '/resources'
    | '/diagnostics/allergy-testing'
    | '/diagnostics/autonomic-testing'
    | '/diagnostics/biomarkers'
    | '/diagnostics/cancer-screening'
    | '/diagnostics/imaging-cardiac'
    | '/diagnostics/sample-report'
    | '/diagnostics/sleep-pulmonary'
    | '/specialties/cardiology-vascular'
    | '/specialties/neurology'
    | '/specialties/pain-management'
    | '/specialties/primary-care'
    | '/specialties/sleep-medicine'
    | '/diagnostics'
    | '/specialties'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/locations'
    | '/longevity'
    | '/resources'
    | '/specialties'
    | '/diagnostics/allergy-testing'
    | '/diagnostics/autonomic-testing'
    | '/diagnostics/biomarkers'
    | '/diagnostics/cancer-screening'
    | '/diagnostics/imaging-cardiac'
    | '/diagnostics/sample-report'
    | '/diagnostics/sleep-pulmonary'
    | '/specialties/cardiology-vascular'
    | '/specialties/neurology'
    | '/specialties/pain-management'
    | '/specialties/primary-care'
    | '/specialties/sleep-medicine'
    | '/diagnostics/'
    | '/specialties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRouteWithChildren
  LocationsRoute: typeof LocationsRoute
  LongevityRoute: typeof LongevityRoute
  ResourcesRoute: typeof ResourcesRoute
  SpecialtiesRoute: typeof SpecialtiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialties': {
      id: '/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof SpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/longevity': {
      id: '/longevity'
      path: '/longevity'
      fullPath: '/longevity'
      preLoaderRoute: typeof LongevityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialties/': {
      id: '/specialties/'
      path: '/'
      fullPath: '/specialties/'
      preLoaderRoute: typeof SpecialtiesIndexRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/diagnostics/': {
      id: '/diagnostics/'
      path: '/'
      fullPath: '/diagnostics/'
      preLoaderRoute: typeof DiagnosticsIndexRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
    '/specialties/sleep-medicine': {
      id: '/specialties/sleep-medicine'
      path: '/sleep-medicine'
      fullPath: '/specialties/sleep-medicine'
      preLoaderRoute: typeof SpecialtiesSleepMedicineRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/primary-care': {
      id: '/specialties/primary-care'
      path: '/primary-care'
      fullPath: '/specialties/primary-care'
      preLoaderRoute: typeof SpecialtiesPrimaryCareRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/pain-management': {
      id: '/specialties/pain-management'
      path: '/pain-management'
      fullPath: '/specialties/pain-management'
      preLoaderRoute: typeof SpecialtiesPainManagementRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/neurology': {
      id: '/specialties/neurology'
      path: '/neurology'
      fullPath: '/specialties/neurology'
      preLoaderRoute: typeof SpecialtiesNeurologyRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/specialties/cardiology-vascular': {
      id: '/specialties/cardiology-vascular'
      path: '/cardiology-vascular'
      fullPath: '/specialties/cardiology-vascular'
      preLoaderRoute: typeof SpecialtiesCardiologyVascularRouteImport
      parentRoute: typeof SpecialtiesRoute
    }
    '/diagnostics/sleep-pulmonary': {
      id: '/diagnostics/sleep-pulmonary'
      path: '/sleep-pulmonary'
      fullPath: '/diagnostics/sleep-pulmonary'
      preLoaderRoute: typeof DiagnosticsSleepPulmonaryRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
    '/diagnostics/sample-report': {
      id: '/diagnostics/sample-report'
      path: '/sample-report'
      fullPath: '/diagnostics/sample-report'
      preLoaderRoute: typeof DiagnosticsSampleReportRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
    '/diagnostics/imaging-cardiac': {
      id: '/diagnostics/imaging-cardiac'
      path: '/imaging-cardiac'
      fullPath: '/diagnostics/imaging-cardiac'
      preLoaderRoute: typeof DiagnosticsImagingCardiacRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
    '/diagnostics/cancer-screening': {
      id: '/diagnostics/cancer-screening'
      path: '/cancer-screening'
      fullPath: '/diagnostics/cancer-screening'
      preLoaderRoute: typeof DiagnosticsCancerScreeningRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
    '/diagnostics/biomarkers': {
      id: '/diagnostics/biomarkers'
      path: '/biomarkers'
      fullPath: '/diagnostics/biomarkers'
      preLoaderRoute: typeof DiagnosticsBiomarkersRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
    '/diagnostics/autonomic-testing': {
      id: '/diagnostics/autonomic-testing'
      path: '/autonomic-testing'
      fullPath: '/diagnostics/autonomic-testing'
      preLoaderRoute: typeof DiagnosticsAutonomicTestingRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
    '/diagnostics/allergy-testing': {
      id: '/diagnostics/allergy-testing'
      path: '/allergy-testing'
      fullPath: '/diagnostics/allergy-testing'
      preLoaderRoute: typeof DiagnosticsAllergyTestingRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
  }
}

interface DiagnosticsRouteChildren {
  DiagnosticsAllergyTestingRoute: typeof DiagnosticsAllergyTestingRoute
  DiagnosticsAutonomicTestingRoute: typeof DiagnosticsAutonomicTestingRoute
  DiagnosticsBiomarkersRoute: typeof DiagnosticsBiomarkersRoute
  DiagnosticsCancerScreeningRoute: typeof DiagnosticsCancerScreeningRoute
  DiagnosticsImagingCardiacRoute: typeof DiagnosticsImagingCardiacRoute
  DiagnosticsSampleReportRoute: typeof DiagnosticsSampleReportRoute
  DiagnosticsSleepPulmonaryRoute: typeof DiagnosticsSleepPulmonaryRoute
  DiagnosticsIndexRoute: typeof DiagnosticsIndexRoute
}

const DiagnosticsRouteChildren: DiagnosticsRouteChildren = {
  DiagnosticsAllergyTestingRoute: DiagnosticsAllergyTestingRoute,
  DiagnosticsAutonomicTestingRoute: DiagnosticsAutonomicTestingRoute,
  DiagnosticsBiomarkersRoute: DiagnosticsBiomarkersRoute,
  DiagnosticsCancerScreeningRoute: DiagnosticsCancerScreeningRoute,
  DiagnosticsImagingCardiacRoute: DiagnosticsImagingCardiacRoute,
  DiagnosticsSampleReportRoute: DiagnosticsSampleReportRoute,
  DiagnosticsSleepPulmonaryRoute: DiagnosticsSleepPulmonaryRoute,
  DiagnosticsIndexRoute: DiagnosticsIndexRoute,
}

const DiagnosticsRouteWithChildren = DiagnosticsRoute._addFileChildren(
  DiagnosticsRouteChildren,
)

interface SpecialtiesRouteChildren {
  SpecialtiesCardiologyVascularRoute: typeof SpecialtiesCardiologyVascularRoute
  SpecialtiesNeurologyRoute: typeof SpecialtiesNeurologyRoute
  SpecialtiesPainManagementRoute: typeof SpecialtiesPainManagementRoute
  SpecialtiesPrimaryCareRoute: typeof SpecialtiesPrimaryCareRoute
  SpecialtiesSleepMedicineRoute: typeof SpecialtiesSleepMedicineRoute
  SpecialtiesIndexRoute: typeof SpecialtiesIndexRoute
}

const SpecialtiesRouteChildren: SpecialtiesRouteChildren = {
  SpecialtiesCardiologyVascularRoute: SpecialtiesCardiologyVascularRoute,
  SpecialtiesNeurologyRoute: SpecialtiesNeurologyRoute,
  SpecialtiesPainManagementRoute: SpecialtiesPainManagementRoute,
  SpecialtiesPrimaryCareRoute: SpecialtiesPrimaryCareRoute,
  SpecialtiesSleepMedicineRoute: SpecialtiesSleepMedicineRoute,
  SpecialtiesIndexRoute: SpecialtiesIndexRoute,
}

const SpecialtiesRouteWithChildren = SpecialtiesRoute._addFileChildren(
  SpecialtiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRouteWithChildren,
  LocationsRoute: LocationsRoute,
  LongevityRoute: LongevityRoute,
  ResourcesRoute: ResourcesRoute,
  SpecialtiesRoute: SpecialtiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
